import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json'

export default function Home() {
  console.log(' products ', products)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The best space jellyfish swag on the web!
        </h1>

        <ul className={styles.grid}>
          {products?.map((products) => {
            const { title, description, image, price, id } = products
            return (
              <li className={styles.card} key={id}>
                <a href="https://nextjs.org/docs">
                  <Image src={image} alt="" width={75} height={75} />
                  <h2>{title}</h2>
                  <p>${price}</p>
                  <p>{description}</p>
                </a>
              </li>
            )
          })}
          <li className={styles.card}>
            <a href="https://nextjs.org/docs">
              <Image
                src="/images/spacejelly-combo.jpg"
                alt=""
                width={75}
                height={75}
              />
              <h2>Space Jelly Tshirt</h2>
              <p>
                Bring Cosmo the space Jellyfish to your wardrobe with this high
                quality tshirt.
              </p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="https://nextjs.org/learn">
              <Image
                src="/images/spacejelly-stickers.jpg"
                alt=""
                width={75}
                height={75}
              />
              <h2>Space Jelly Stickers</h2>
              <p>
                Add some flare to your laptop with a sticker of Cosmo the Space
                Jellyfish.
              </p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="https://github.com/vercel/next.js/tree/canary/examples">
              <Image
                src="/images/spacejelly-tshirt.jpg"
                alt=""
                width={75}
                height={75}
              />
              <h2>Space Jelly Combo</h2>
              <p>
                Show your love for Cosmo with a tshirt and sticker combo pack!
              </p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
