import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json';

import { useCart } from '../hooks/use-cart'

export default function Home() {
    const { subtotal, totalItems, checkout, addToCart} = useCart();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Space Jelly Shop
                </h1>

                <p className={styles.description}>
                    <strong>Items:</strong> { totalItems }
                    <br/>
                    <strong>Total Cost:</strong> ${subtotal}
                    <br/>
                    <button className={styles.button} onClick={checkout}>Check out</button>
                </p>

                <p className={styles.description}>
                    The best space jellyfish swag on the web!
                </p>

                <ul className={styles.grid}>
                    {
                        products && products.map(product => {
                            const {id, title, image, description, price} = product;
                            return (
                                <li className={styles.card} key={id}>
                                    <img src={image} alt={title}/>
                                    <h3>{title}</h3>
                                    <p>${price}</p>
                                    <p>{description}</p>
                                    <p>
                                        <button className={styles.button} onClick={() => addToCart({ id})}>Add To Cart</button>
                                    </p>
                                </li>
                            )
                        })
                    }

                </ul>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
